### ISSUE TITLE
Read the paper - I don't even know what to say.

### ISSUE THREAD

**Issue by LelleSwe** [Big-polar-bear/factorization#2]
In short - It's a terrible mess.

Longer: I don't see a problem in using the paper as personal notes. However mathematical - and scientific - papers in general do not display these characteristics. They are by convention depersonalised and very formal, perhaps just below legal texts. If I was grading this it would be a fail on this point alone. Additionally, when performing a mathematical proof, no matter how many examples are provided, you must generalise and not use exclusively examples. Until you find a proof that works for all numbers (or in some clearly defined range) the paper is incomplete. If the issue is with the math jargon itself, the paper is also incomplete until you learn the specifics required to communicate your ideas clearly. Providing examples is a great way to improve learning, but it should _never_ be the only content. Setting this aside, I find myself thoroughly unconvinced of the paper's usefulness. You include a couple more examples of chosen inputs and the corresponding time to factor the number. However all of these test numbers are (in a cryptographic sense) awfully small, and the compute times for them very large. Without proper complexity analysis showing very small scaling I strongly doubt the effectiveness of your algorithm for typically sized keys (thousands of bits for RSA and hundreds for ECC).

**Comment by ripSquid** [comment]
It's honest effort from your side writing the paper. I hope you can delve deeper into writing better proofs of your idea and being able to prove them on bigger keys as to become more relevant in the modern world.

**Comment by Big-polar-bear** [comment]
Blah blah bah
