### ISSUE TITLE
Instability for small (valid & invalid) keys.

### ISSUE THREAD

**Issue by LelleSwe** [Big-polar-bear/factorization#4]
So I wanted to test the effectiveness of the program myself and cloned the repo. The following are some results I've noticed when running standard settings (all times based on my computer):

### Inputting valid numbers:
key= 49 (=7\*7) consistently found 7\*7 and took about 1.7 seconds each time.
key= 25 (=5\*5) consistently crashed the program in 1.5 seconds.
key= 9 (=3\*3) appears to never finish computing.

key= 2 \* a prime seems to consistently crash the program.
key= 15 (=3\*5) or 21 (=3\*7) causes the program to crash.

key= 10027 (=37\*271) seemingly runs forever
key= 53929 (=199\*271) seemingly runs forever
key= 72899 (=269\*271) however was solved in 1.5 seconds

### Inputting unintended numbers:
Inputting a prime will either crash the program or cause it to run indefinitely.
Inputting 0 will cause the program to return a random combination of 2 primes, approximately 100 in size. On my computer this seemed to take anywhere between 0.5 and 20.6 seconds, which is a pretty large time difference.
Inputting any number consisting of more than 2 prime factors either causes the program to run indefinitely, or in some cases may actually find prime factors!

Edit: Formatting

**Comment by Big-polar-bear** [comment]
Yes, its only supposed to work with two factors (since this is what rsa encryption uses and that was the main goal of this research. With more factors the quadratic congruences probably look a little different). 

I had never tested with super small integers. Thanks, I'll make sure those work.
Im currently doing major refactoring, there's a couple of bugs I've already spotted that may cause it to not find factors. Ill release it later this month.

**Comment by Big-polar-bear** [comment]
Fixed issues related to semiprimes (integer made up of two prime factors), as this research was related to RSA and the scope was limited to that. Additionally, it assumes two factors of similar bit length (as RSA implementations should have), need to change some of the limits/ceilings/floors in the code to extend the search range if factors are spaced out further apart. Have not tested much on integers smaller then 20 bits, as there really isn't much point to it.
